name: Build React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd carzino-plugin/frontend
          npm install

      - name: Build React app
        run: |
          cd carzino-plugin/frontend
          npm run build

      - name: Move build output
        run: |
          rm -rf carzino-plugin/build/*
          cp -r carzino-plugin/frontend/dist/* carzino-plugin/build/

      - name: Commit build output
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add carzino-plugin/build
          git commit -m "Update build output" || echo "No changes to commit"
          git push
